# -*- coding: utf-8 -*-
"""Volume de uma Esfera.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AnsDmbf81s0ZpPpLyD_A23JVtQQDYbT_
"""

print('Cálculo de Volume de uma Esfera')
print('')

raio = float(input('Digite o raio da esfera: '))

volumeEsfera = (4/3)*3.14*raio**3

print("O volume da esfera é: {}".format(volumeEsfera))

